# The experiment folder related to the experiment name. Should be in the same order as experiment_name.yaml
- data/temp/open_the_door_of_the_storagefurniture_by_its_handle_StorageFurniture_41510_2024-03-27-15-59-54/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/temp/open_the_door_of_the_storagefurniture_by_its_handle_StorageFurniture_45448_2024-03-27-22-40-39/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/temp/open_the_door_of_the_storagefurniture_by_its_handle_StorageFurniture_46462_2024-03-27-23-35-10/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/temp/open_the_door_of_the_storagefurniture_by_its_handle_StorageFurniture_46732_2024-03-27-18-46-00/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/temp/open_the_door_of_the_storagefurniture_by_its_handle_StorageFurniture_46801_2024-03-27-20-37-05/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/temp/open_the_door_of_the_storagefurniture_by_its_handle_StorageFurniture_46874_2024-03-27-13-57-49/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/temp/open_the_door_of_the_storagefurniture_by_its_handle_StorageFurniture_46922_2024-03-27-19-42-45/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/temp/open_the_door_of_the_storagefurniture_by_its_handle_StorageFurniture_46966_2024-03-27-16-55-33/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/temp/open_the_door_of_the_storagefurniture_by_its_handle_StorageFurniture_47570_2024-03-27-21-36-50/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/temp/open_the_door_of_the_storagefurniture_by_its_handle_StorageFurniture_47578_2024-03-27-14-56-07/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/temp/open_the_door_of_the_storagefurniture_by_its_handle_StorageFurniture_48700_2024-03-27-12-59-58/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/diverse_objects/open_the_door_45526/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/diverse_objects/open_the_door_45661/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/diverse_objects/open_the_door_45694/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/diverse_objects/open_the_door_45780/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/diverse_objects/open_the_door_45910/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/diverse_objects/open_the_door_45961/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/diverse_objects/open_the_door_46408/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/diverse_objects/open_the_door_46417/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/diverse_objects/open_the_door_46440/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/diverse_objects/open_the_door_46490/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/diverse_objects/open_the_door_46762/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/diverse_objects/open_the_door_46825/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/diverse_objects/open_the_door_46893/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/diverse_objects/open_the_door_47235/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/diverse_objects/open_the_door_47281/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/diverse_objects/open_the_door_47315/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/diverse_objects/open_the_door_47529/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/diverse_objects/open_the_door_47669/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/diverse_objects/open_the_door_47944/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/diverse_objects/open_the_door_48063/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/diverse_objects/open_the_door_48177/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/diverse_objects/open_the_door_48356/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/diverse_objects/open_the_door_48623/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/diverse_objects/open_the_door_48876/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/diverse_objects/open_the_door_49025/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/diverse_objects/open_the_door_49062/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/diverse_objects/open_the_door_49132/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/diverse_objects/open_the_door_49133/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/diverse_objects_2/open_the_door_40417/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/diverse_objects_2/open_the_door_41085/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/diverse_objects_2/open_the_door_41452/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/diverse_objects_2/open_the_door_45162/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/diverse_objects_2/open_the_door_45176/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/diverse_objects_2/open_the_door_45194/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/diverse_objects_2/open_the_door_45203/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/diverse_objects_2/open_the_door_45248/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/diverse_objects_2/open_the_door_45271/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/diverse_objects_2/open_the_door_45290/task_open_the_door_of_the_storagefurniture_by_its_handle
- data/diverse_objects_2/open_the_door_45305/task_open_the_door_of_the_storagefurniture_by_its_handle