_target_: diffusion_policy_3d.dataset.robogen_dataset.RobogenDataset
horizon: ${horizon}
pad_before: ${eval:'${n_obs_steps}-1'}
pad_after: ${eval:'${n_action_steps}-1'}
seed: 42
val_ratio: 0.1
train_ratio: 0.9
max_train_episodes: null
observation_mode: act3d_goal_mlp
enumerate: true
kept_in_disk: true
load_per_step: true
is_pickle: true
num_load_episodes: 1000
dataset_keys: ['state', 'action', 'point_cloud', 'gripper_pcd', 'displacement_gripper_to_object', 'goal_gripper_pcd']
zarr_path:
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0626-act3d-obj-41510-per-step-combine-2-action-gripper-goal-displacement-to-closest-obj-point-filtered-zero-closing-action
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0622-act3d-obj-45448-remove-reaching-collision-resize-2-full-per-step-gripper-goal-displacement-to-closest-obj-point
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0624-act3d-obj-46462-per-step-combine-2-action-gripper-goal-displacement-to-closest-obj-point-filtered-zero-closing-action
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0628-act3d-obj-46732-gripper-goal-1-displacement-to-object-1-combined-steps-2-filter-zero-close-action-1
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0628-act3d-obj-46801-gripper-goal-1-displacement-to-object-1-combined-steps-2-filter-zero-close-action-1
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0628-act3d-obj-46874-gripper-goal-1-displacement-to-object-1-combined-steps-2-filter-zero-close-action-1
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0628-act3d-obj-46922-gripper-goal-1-displacement-to-object-1-combined-steps-2-filter-zero-close-action-1
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0628-act3d-obj-46966-gripper-goal-1-displacement-to-object-1-combined-steps-2-filter-zero-close-action-1
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0628-act3d-obj-47570-gripper-goal-1-displacement-to-object-1-combined-steps-2-filter-zero-close-action-1
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0628-act3d-obj-47578-gripper-goal-1-displacement-to-object-1-combined-steps-2-filter-zero-close-action-1
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0628-act3d-obj-48700-gripper-goal-1-displacement-to-object-1-combined-steps-2-filter-zero-close-action-1
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0705-obj-45526
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0705-obj-45661
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0705-obj-45694
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0705-obj-45780
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0705-obj-45910
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0705-obj-45961
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0705-obj-46408
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0705-obj-46417
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0705-obj-46440
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0705-obj-46490
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0705-obj-46762
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0705-obj-46825
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0705-obj-46893
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0705-obj-47235
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0705-obj-47281
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0705-obj-47315
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0705-obj-47529
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0705-obj-47669
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0705-obj-47944
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0705-obj-48063
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0705-obj-48177
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0705-obj-48356
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0705-obj-48623
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0705-obj-48876
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0705-obj-49025
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0705-obj-49062
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0705-obj-49132
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0705-obj-49133
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0712-obj-40417
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0712-obj-41085
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0712-obj-41452
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0712-obj-45162
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0712-obj-45176
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0712-obj-45194
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0712-obj-45203
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0712-obj-45248
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0712-obj-45271
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0712-obj-45290
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0712-obj-45305
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0725-obj-45427
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0725-obj-45620
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0725-obj-45623
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0725-obj-45636
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0725-obj-45689
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0725-obj-45696
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0725-obj-45749
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0725-obj-45759
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0725-obj-45936
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0725-obj-45984
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0725-obj-46130
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0725-obj-46197
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0725-obj-46481
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0725-obj-46544
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0725-obj-47178
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0725-obj-47182
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0725-obj-47227
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0725-obj-47577
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0725-obj-47648
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0725-obj-47747
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0725-obj-47808
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0725-obj-47976
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0725-obj-48010
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0725-obj-48258
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0725-obj-48379
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0725-obj-48797
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0725-obj-48855
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0725-obj-48859
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0725-obj-49188
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-35059
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-41004
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-41083
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-44781
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-44826
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-44853
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45092
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45130
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45135
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45146
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45164
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45168
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45173
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45212
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45213
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45372
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45374
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45387
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45415
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45419
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45423
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45503
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45505
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45524
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45573
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45575
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45606
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45612
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45621
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45622
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45632
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45638
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45645
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45662
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45671
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45676
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45677
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45687
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45699
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45710
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45746
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45756
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45783
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45784
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45790
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45801
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45822
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45853
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45855
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45915
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45948
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45949
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45963
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-45964
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-46019
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-46029
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-46033
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-46037
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-46044
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-46045
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-46060
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-46084
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-46108
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-46117
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-46120
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-46123
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-46145
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-46179
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-46180
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-46199
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-46380
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-46427
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-46430
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-46439
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-46537
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-46549
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-46556
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-46598
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-46616
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-46699
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-46700
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-46741
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-46744
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-46847
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-46856
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-46859
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-46889
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-46906
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-46944
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-46955
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-46981
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-47024
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-47089
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-47183
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-47207
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-47233
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-47252
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-47278
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-47290
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-47296
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-47438
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-47514
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-47595
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-47601
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-47729
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-47853
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-47926
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-48413
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-48452
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-48467
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-48490
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-48513
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-48517
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-48721
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-48746
- /scratch/mnakuraf/data/dp3_demo_combine_4_dense_10/0730-obj-48878