# This is used for training. This is the extracted data from the experiments file
- /scratch/chialiang/dp3_demo/0705-obj-41510
- /scratch/chialiang/dp3_demo/0705-obj-45448
- /scratch/chialiang/dp3_demo/0705-obj-46462
- /scratch/chialiang/dp3_demo/0705-obj-46732
- /scratch/chialiang/dp3_demo/0705-obj-46801
- /scratch/chialiang/dp3_demo/0705-obj-46874
- /scratch/chialiang/dp3_demo/0705-obj-46922
- /scratch/chialiang/dp3_demo/0705-obj-46966
- /scratch/chialiang/dp3_demo/0705-obj-47570
- /scratch/chialiang/dp3_demo/0705-obj-47578
- /scratch/chialiang/dp3_demo/0705-obj-48700
- /scratch/chialiang/dp3_demo/0705-obj-45526
- /scratch/chialiang/dp3_demo/0705-obj-45661
- /scratch/chialiang/dp3_demo/0705-obj-45694
- /scratch/chialiang/dp3_demo/0705-obj-45780
- /scratch/chialiang/dp3_demo/0705-obj-45910
- /scratch/chialiang/dp3_demo/0705-obj-45961
- /scratch/chialiang/dp3_demo/0705-obj-46408
- /scratch/chialiang/dp3_demo/0705-obj-46417
- /scratch/chialiang/dp3_demo/0705-obj-46440
- /scratch/chialiang/dp3_demo/0705-obj-46490
- /scratch/chialiang/dp3_demo/0705-obj-46762
- /scratch/chialiang/dp3_demo/0705-obj-46825
- /scratch/chialiang/dp3_demo/0705-obj-46893
- /scratch/chialiang/dp3_demo/0705-obj-47235
- /scratch/chialiang/dp3_demo/0705-obj-47281
- /scratch/chialiang/dp3_demo/0705-obj-47315
- /scratch/chialiang/dp3_demo/0705-obj-47529
- /scratch/chialiang/dp3_demo/0705-obj-47669
- /scratch/chialiang/dp3_demo/0705-obj-47944
- /scratch/chialiang/dp3_demo/0705-obj-48063
- /scratch/chialiang/dp3_demo/0705-obj-48177
- /scratch/chialiang/dp3_demo/0705-obj-48356
- /scratch/chialiang/dp3_demo/0705-obj-48623
- /scratch/chialiang/dp3_demo/0705-obj-48876
- /scratch/chialiang/dp3_demo/0705-obj-49025
- /scratch/chialiang/dp3_demo/0705-obj-49062
- /scratch/chialiang/dp3_demo/0705-obj-49132
- /scratch/chialiang/dp3_demo/0705-obj-49133
- /scratch/chialiang/dp3_demo/0712-obj-40417
- /scratch/chialiang/dp3_demo/0712-obj-41085
- /scratch/chialiang/dp3_demo/0712-obj-41452
- /scratch/chialiang/dp3_demo/0712-obj-45162
- /scratch/chialiang/dp3_demo/0712-obj-45176
- /scratch/chialiang/dp3_demo/0712-obj-45194
- /scratch/chialiang/dp3_demo/0712-obj-45203
- /scratch/chialiang/dp3_demo/0712-obj-45248
- /scratch/chialiang/dp3_demo/0712-obj-45271
- /scratch/chialiang/dp3_demo/0712-obj-45290
- /scratch/chialiang/dp3_demo/0712-obj-45305